apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g2x8q9kbs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g2x8q9kbs-go 
  name: g2x8q9kbs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g2x8q9kbs-go 
